name: Test deployed API

on:
  workflow_dispatch:
    inputs:
      SWAGGER_URL:
        description: Remote API to test
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: teritorio/elasa-api-test@master
      with:
        SWAGGER_URL: ${{ github.event.inputs.SWAGGER_URL }}
