name: Test deployed API

on:
  workflow_dispatch:
    inputs:
      ONTOLOGY_URL:
        description: Ontology json
        required: true
        default: https://teritorio.github.io/ontology-builder/teritorio-tourism-ontology-1.0.json
      SWAGGER_URL:
        description: Remote API to test
        required: true
        default: https://elasa-dev.teritorio.xyz/static/elasa-0.1.swagger.yaml
      API_URL:
        description: Remote API to test
        required: true
        default: https://elasa-dev.teritorio.xyz/api/0.1/pointsdevue_eus/tourism

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: teritorio/elasa-api-test@master
      with:
        ONTOLOGY_URL: ${{ github.event.inputs.ONTOLOGY_URL }}
        SWAGGER_URL: ${{ github.event.inputs.SWAGGER_URL }}
